### ISSUE TITLE
Back-end for user registration and login

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-macchiato#9]
- User model -> name, hashed password (bcrypt), etc..
- /register
    - Validation (4xx) (password length, email formatting, confirm password is the same as password), create a new user (201), generate a JWT token, return the user and the token (stored in the front-end in local or sessionStorage) 
- /login
    - verify password / email and return 200, generate a JWT token, return the user and the token (stored in the front-end in local or sessionStorage)

**Comment by d-ang1993** [comment]
Hey Shums! Just a quick q, 
_confirm password is the same as password_ -
Is this just validating when a user needs to enter their password twice when register for an account?
